@host=https://localhost:7168

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Ayrton",
    "lastName": "Senna",
    "email": "ayrton.senna@email.com",
    "password": "Ayrton123!"
}